require:
  - rubocop-performance
  - rubocop-rake
  - rubocop-rails
  - rubocop-rspec

AllCops:
  Exclude:
    - 'config/**/*'
    - 'db/**/*'
    - 'bin/**/*'
    - 'config.ru'

Style/Documentation:
  Enabled: false
